### ISSUE TITLE
bsTooltip error

### ISSUE THREAD

**Issue by kuzmenkov111** [ebailey78/shinyBS#89]
Hi! Thank you for great job! 
I have some problem... bsTooltip does not appear in app and in brouser console I have error:  
`Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'
    at Function.error (http://127.0.0.1:4546/shared/jquery.min.js:2:1814)
    at HTMLDivElement.<anonymous> (http://127.0.0.1:4546/shared/jqueryui/jquery-ui.min.js:6:5615)
    at Function.each (http://127.0.0.1:4546/shared/jquery.min.js:2:2881)
    at n.fn.init.each (http://127.0.0.1:4546/shared/jquery.min.js:2:846)
    at n.fn.init.t.fn.(anonymous function) [as tooltip] (http://127.0.0.1:4546/shared/jqueryui/jquery-ui.min.js:6:5357)
    at Object.shinyBS.addTooltip (http://127.0.0.1:4546/sbs/shinyBS.js:204:9)
    at http://127.0.0.1:4546/:333:92`

**Comment by LuShuYangMing** [comment]
so do I
